apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090

