apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devops-tools
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # Uncomment and set your Alertmanager target if you have one:
              # - alertmanager:9093

    rule_files:
      - "alert.rules.yml"

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["10.244.1.6:9090"]

      - job_name: "node_exporter"
        static_configs:
          - targets: ["10.244.1.6:9100"]

