apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: devops-tools
spec:
  type: NodePort
  ports:
  - name: http
    port: 9100
    targetPort: 9100
    nodePort: 30003
  selector:
    app: node-exporter

