apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
        args:
        - --collector.textfile.directory=/host/project/nodeport_exporter/textfile_collector
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 0
        volumeMounts:
            - name: nodeport-exporter
              mountPath: /host/project/nodeport_exporter/
      volumes:
      - name: nodeport-exporter
        persistentVolumeClaim:
          claimName: node-exporter-pv-claim
  
