apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-exporter-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /project/nodeport_exporter
  storageClassName: local-storage

